### ISSUE TITLE
Do we need Google Fit App for Google Fit API?

### ISSUE THREAD

**Issue by ghost** [googlearchive/android-fit#53]
I made small test app which shows daily steps using Google Fit API. During testing, I was not getting any steps count. But later I realised that my Samsung device doesn't come's with Google Fit app so I downloaded it and after feeding some data then I tested my app again and Now I can see my steps count on my test app.

So Does this means that in order to use Google Fit API all my app users must have installed Google Fit App?

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!

**Comment by mlazari** [comment]
@hienttVFJ See https://github.com/android/fit/issues/33#issuecomment-530767796
